---
repos:
  # install pr-commit with pip install pre-commit
  # pre-commit install --all to install whatever in .pre-commit-config.yaml
  # pre-commit run --all-files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args: [--severity, "error"]
        exclude: "^.git"
        files: "\\.sh$"

  # pip install detect-secrets
  # detect-secrets scan > .secrets.baseline
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # args: ['--baseline', '.secrets.baseline']
        args: ['scan']

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.36.2
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint"]

  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        args: ["-conf", ".yamlfmt"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
        args: ["--pre-commit", "--redact", "--staged", "--verbose"]
  # gem needs to be installed
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        # insted of args, use the .mdlrc
        #args: ["-r", "~MD007,~MD013"]

  # need the hadolit installed
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint
        files: (Dockerfile.*|.*/Dockerfile)
